jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: Nfsaavedra/workflow-telemetry-action@raw_data
      with:
        save_raw_stats: true
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        allow-prereleases: true
        python-version: 3.12
    - uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        path: ~/.cache/pip
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip setuptools six wheel

        python -m pip install pytest-cov -r requirements.txt

        '
    - name: Run tests
      run: pytest --ignore=quantum/q_fourier_transform.py --ignore=project_euler/
        --ignore=scripts/validate_solutions.py --cov-report=term-missing:skip-covered
        --cov=. .
    - if: ${{ success() }}
      run: scripts/build_directory_md.py 2>&1 | tee DIRECTORY.md
name: build
'on':
- workflow_dispatch
permissions: write-all
